(
    'address1', 'address2', 'city', 'state', 'zip', 'country', 'phone', 'fax', 'website',
    'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp',
    'longBusinessSummary', 'companyOfficers', 'executiveTeam', 'maxAge', 'priceHint',
    'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose',
    'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate',
    'dividendYield', 'exDividendDate', 'beta', 'trailingPE', 'volume', 'regularMarketVolume',
    'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask',
    'marketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'priceToSalesTrailing12Months',
    'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate',
    'trailingAnnualDividendYield', 'currency', 'tradeable', 'enterpriseValue',
    'profitMargins', 'sharesOutstanding', 'heldPercentInsiders', 'heldPercentInstitutions',
    'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd',
    'nextFiscalYearEnd', 'netIncomeToCommon', 'trailingEps', 'enterpriseToRevenue',
    '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate',
    'quoteType', 'currentPrice', 'recommendationKey', 'quickRatio', 'currentRatio',
    'totalRevenue', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits',
    'freeCashflow', 'operatingCashflow', 'grossMargins', 'ebitdaMargins', 'operatingMargins',
    'financialCurrency', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName',
    'triggerable', 'customPriceAlertConfidence', 'shortName', 'exchange', 'messageBoardId',
    'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market',
    'esgPopulated', 'longName', 'marketState', 'regularMarketChangePercent',
    'regularMarketPrice', 'regularMarketTime', 'corporateActions', 'fiftyDayAverageChange',
    'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange',
    'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy',
    'prevName', 'nameChangeDate', 'cryptoTradeable', 'regularMarketChange',
    'regularMarketDayRange', 'fullExchangeName', 'averageDailyVolume3Month',
    'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange',
    'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent',
    'epsTrailingTwelveMonths', 'hasPrePostMarketData', 'firstTradeDateMilliseconds',
    'trailingPegRatio', 'payoutRatio', 'bidSize', 'askSize'
)
